spring:
  profiles:
    #激活开发环境
    active: dev
---
#开发环境配置
spring:
  profiles: dev
  devtools:
    restart:
      additional-paths: src/main/java
  thymeleaf:
    suffix: .html
    cache: false
    servlet:
      content-type: text/html
    encoding: UTF-8
    mode: HTML5

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/platform?serverTimezone=UTC
    username: root
    password: wangjile
  redis:
    database: 0
    host: localhost
    port: 6379

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  main:
    allow-bean-definition-overriding: true
server:
  port: 8081
---
#生产环境配置
spring:
  profiles: pro
server:
  port: 8082